#!/bin/bash

# To use important variables from command line use the following code:
COMMAND=$0    # Zero argument is shell command
PTEMPDIR=$1   # First argument is temp folder during install
PSHNAME=$2    # Second argument is Plugin-Name for scipts etc.
PDIR=$3       # Third argument is Plugin installation folder
PVERSION=$4   # Forth argument is Plugin version
#LBHOMEDIR=$5 # Comes from /etc/environment now. Fifth argument is
              # Base folder of LoxBerry
PTEMPPATH=$6  # Sixth argument is full temp path during install (see also $1)

# Combine them with /etc/environment
PHTMLAUTH=$LBHOMEDIR/webfrontend/htmlauth/plugins/$PDIR
PHTML=$LBPHTML/$PDIR
PTEMPL=$LBPTEMPL/$PDIR
PDATA=$LBPDATA/$PDIR
PLOGS=$LBPLOG/$PDIR # Note! This is stored on a Ramdisk now!
PCONFIG=$LBPCONFIG/$PDIR
PSBIN=$LBPSBIN/$PDIR
PBIN=$LBPBIN/$PDIR

echo "<INFO> Stop LoxBuddy Server..."
npm --prefix $PBIN/server run kill

echo "<INFO> Uninstall local Node.js packages..."
npm --prefix $PBIN/server uninstall loxbuddy_server

echo "<INFO> Uninstall Apache2 site..."
a2dissite 001-$PDIR > /dev/null 2>&1
rm $LBHOMEDIR/system/apache2/sites-available/001-$PDIR.conf > /dev/null 2>&1
service apache2 reload > /dev/null 2>&1

# Exit with Status 0
exit 0
